// Fixture data used when live scraping is disabled or blocked.
// Each item is a fully-normalized listing for one source site.

const IMG = (seed) => `https://picsum.photos/seed/${seed}/800/600`;

const CARS_COM = [
  {
    listingId: 'cars-1001',
    title: '2022 Toyota RAV4 XLE Premium',
    year: 2022, make: 'Toyota', model: 'RAV4', trim: 'XLE Premium',
    price: 31995, mileage: 18420,
    bodyStyle: 'SUV', transmission: 'Automatic', fuelType: 'Gas', drivetrain: 'AWD',
    exteriorColor: 'Silver Sky Metallic', interiorColor: 'Black',
    engine: '2.5L I4', mpgCity: 27, mpgHighway: 35,
    location: 'Austin, TX', dealerName: 'Lone Star Toyota', dealerPhone: '(512) 555-0142',
    description: 'One-owner RAV4 XLE Premium with sunroof, heated seats, and adaptive cruise control. Clean Carfax.',
    imageUrl: IMG('rav4-1'), images: [IMG('rav4-1'), IMG('rav4-1b'), IMG('rav4-1c')],
    sourceUrl: 'https://www.cars.com/vehicledetail/cars-1001/',
    sourceSite: 'Cars.com',
    vin: 'JTMRWRFV2ND123456',
  },
  {
    listingId: 'cars-1002',
    title: '2020 Honda Civic EX',
    year: 2020, make: 'Honda', model: 'Civic', trim: 'EX',
    price: 21450, mileage: 41230,
    bodyStyle: 'Sedan', transmission: 'CVT', fuelType: 'Gas', drivetrain: 'FWD',
    exteriorColor: 'Cosmic Blue', interiorColor: 'Gray',
    engine: '1.5L Turbo I4', mpgCity: 32, mpgHighway: 42,
    location: 'San Jose, CA', dealerName: 'Bay Area Honda', dealerPhone: '(408) 555-0188',
    description: 'Well-maintained Civic EX, sunroof, Honda Sensing safety suite, single-owner trade-in.',
    imageUrl: IMG('civic-2'), images: [IMG('civic-2')],
    sourceUrl: 'https://www.cars.com/vehicledetail/cars-1002/',
    sourceSite: 'Cars.com',
    vin: '2HGFC2F69LH123456',
  },
  {
    listingId: 'cars-1003',
    title: '2023 Ford F-150 XLT SuperCrew',
    year: 2023, make: 'Ford', model: 'F-150', trim: 'XLT SuperCrew',
    price: 47990, mileage: 9120,
    bodyStyle: 'Truck', transmission: 'Automatic', fuelType: 'Gas', drivetrain: '4WD',
    exteriorColor: 'Oxford White', interiorColor: 'Medium Earth Gray',
    engine: '3.5L EcoBoost V6', mpgCity: 18, mpgHighway: 24,
    location: 'Denver, CO', dealerName: 'Mile High Ford', dealerPhone: '(303) 555-0199',
    description: 'Like-new F-150 XLT with tow package, FX4 off-road, and 360-degree camera.',
    imageUrl: IMG('f150-3'), images: [IMG('f150-3'), IMG('f150-3b')],
    sourceUrl: 'https://www.cars.com/vehicledetail/cars-1003/',
    sourceSite: 'Cars.com',
    vin: '1FTFW1E8XPFA12345',
  },
  {
    listingId: 'cars-1004',
    title: '2021 Tesla Model 3 Long Range',
    year: 2021, make: 'Tesla', model: 'Model 3', trim: 'Long Range',
    price: 33490, mileage: 27800,
    bodyStyle: 'Sedan', transmission: 'Automatic', fuelType: 'Electric', drivetrain: 'AWD',
    exteriorColor: 'Pearl White', interiorColor: 'Black',
    engine: 'Dual Motor Electric', mpgCity: 134, mpgHighway: 126,
    location: 'Seattle, WA', dealerName: 'EV Auto Group', dealerPhone: '(206) 555-0144',
    description: 'Tesla Model 3 LR AWD, premium interior, autopilot, full charge history available.',
    imageUrl: IMG('model3-4'), images: [IMG('model3-4')],
    sourceUrl: 'https://www.cars.com/vehicledetail/cars-1004/',
    sourceSite: 'Cars.com',
    vin: '5YJ3E1EB6MF123456',
  },
  {
    listingId: 'cars-1005',
    title: '2019 Subaru Outback 2.5i Limited',
    year: 2019, make: 'Subaru', model: 'Outback', trim: '2.5i Limited',
    price: 22950, mileage: 58900,
    bodyStyle: 'Wagon', transmission: 'CVT', fuelType: 'Gas', drivetrain: 'AWD',
    exteriorColor: 'Crystal Black', interiorColor: 'Java Brown',
    engine: '2.5L H4', mpgCity: 25, mpgHighway: 32,
    location: 'Portland, OR', dealerName: 'Cascade Subaru', dealerPhone: '(503) 555-0166',
    description: 'Outback Limited with EyeSight, leather, heated seats, and roof rails.',
    imageUrl: IMG('outback-5'), images: [IMG('outback-5')],
    sourceUrl: 'https://www.cars.com/vehicledetail/cars-1005/',
    sourceSite: 'Cars.com',
    vin: '4S4BSANC9K3123456',
  },
];

const CARGURUS = [
  {
    // duplicate of cars-1001 (RAV4) at slightly different price/mileage – tests dedup
    listingId: 'cg-2001',
    title: '2022 Toyota RAV4 XLE Premium',
    year: 2022, make: 'Toyota', model: 'RAV4', trim: 'XLE Premium',
    price: 31750, mileage: 18510,
    bodyStyle: 'SUV', transmission: 'Automatic', fuelType: 'Gas', drivetrain: 'AWD',
    exteriorColor: 'Silver', interiorColor: 'Black',
    engine: '2.5L I4', mpgCity: 27, mpgHighway: 35,
    location: 'Austin, TX', dealerName: 'Lone Star Toyota', dealerPhone: '(512) 555-0142',
    description: 'XLE Premium AWD – sunroof, blind-spot monitor, power liftgate.',
    imageUrl: IMG('rav4-1'), images: [IMG('rav4-1')],
    sourceUrl: 'https://www.cargurus.com/Cars/inventorylisting/viewDetailsFilterViewInventoryListing.action?listingId=cg-2001',
    sourceSite: 'CarGurus',
    vin: 'JTMRWRFV2ND123456',
  },
  {
    listingId: 'cg-2002',
    title: '2018 BMW 3 Series 330i xDrive',
    year: 2018, make: 'BMW', model: '3 Series', trim: '330i xDrive',
    price: 23990, mileage: 62100,
    bodyStyle: 'Sedan', transmission: 'Automatic', fuelType: 'Gas', drivetrain: 'AWD',
    exteriorColor: 'Alpine White', interiorColor: 'Coral Red',
    engine: '2.0L Turbo I4', mpgCity: 23, mpgHighway: 34,
    location: 'Chicago, IL', dealerName: 'Lakeshore Auto', dealerPhone: '(312) 555-0177',
    description: '330i xDrive with M Sport package, navigation, premium audio.',
    imageUrl: IMG('bmw-2'), images: [IMG('bmw-2')],
    sourceUrl: 'https://www.cargurus.com/Cars/inventorylisting/viewDetailsFilterViewInventoryListing.action?listingId=cg-2002',
    sourceSite: 'CarGurus',
    vin: 'WBA8D9G54JA123456',
  },
  {
    listingId: 'cg-2003',
    title: '2020 Jeep Wrangler Unlimited Sport',
    year: 2020, make: 'Jeep', model: 'Wrangler', trim: 'Unlimited Sport',
    price: 32450, mileage: 38400,
    bodyStyle: 'SUV', transmission: 'Automatic', fuelType: 'Gas', drivetrain: '4WD',
    exteriorColor: 'Firecracker Red', interiorColor: 'Black',
    engine: '3.6L V6', mpgCity: 17, mpgHighway: 23,
    location: 'Phoenix, AZ', dealerName: 'Desert Jeep', dealerPhone: '(602) 555-0155',
    description: 'Wrangler Unlimited Sport with hard top, tow package, and trail-rated 4x4.',
    imageUrl: IMG('jeep-3'), images: [IMG('jeep-3')],
    sourceUrl: 'https://www.cargurus.com/Cars/inventorylisting/viewDetailsFilterViewInventoryListing.action?listingId=cg-2003',
    sourceSite: 'CarGurus',
    vin: '1C4HJXDG3LW123456',
  },
  {
    listingId: 'cg-2004',
    title: '2022 Hyundai Ioniq 5 SEL',
    year: 2022, make: 'Hyundai', model: 'Ioniq 5', trim: 'SEL',
    price: 38990, mileage: 12800,
    bodyStyle: 'SUV', transmission: 'Automatic', fuelType: 'Electric', drivetrain: 'RWD',
    exteriorColor: 'Cyber Gray', interiorColor: 'Dark Pebble Gray',
    engine: 'Single Motor 168kW', mpgCity: 110, mpgHighway: 87,
    location: 'Atlanta, GA', dealerName: 'Peachtree EV', dealerPhone: '(404) 555-0133',
    description: 'Ioniq 5 SEL with ultra-fast charging, panoramic sunroof, Highway Driving Assist.',
    imageUrl: IMG('ioniq-4'), images: [IMG('ioniq-4')],
    sourceUrl: 'https://www.cargurus.com/Cars/inventorylisting/viewDetailsFilterViewInventoryListing.action?listingId=cg-2004',
    sourceSite: 'CarGurus',
    vin: 'KM8KNDAF5NU123456',
  },
  {
    listingId: 'cg-2005',
    title: '2017 Mazda MX-5 Miata Club',
    year: 2017, make: 'Mazda', model: 'MX-5 Miata', trim: 'Club',
    price: 19800, mileage: 44900,
    bodyStyle: 'Convertible', transmission: 'Manual', fuelType: 'Gas', drivetrain: 'RWD',
    exteriorColor: 'Soul Red', interiorColor: 'Black',
    engine: '2.0L I4', mpgCity: 26, mpgHighway: 33,
    location: 'San Diego, CA', dealerName: 'Coastal Mazda', dealerPhone: '(619) 555-0122',
    description: 'Iconic MX-5 Club, 6-speed manual, Brembo brakes, BBS wheels.',
    imageUrl: IMG('miata-5'), images: [IMG('miata-5')],
    sourceUrl: 'https://www.cargurus.com/Cars/inventorylisting/viewDetailsFilterViewInventoryListing.action?listingId=cg-2005',
    sourceSite: 'CarGurus',
    vin: 'JM1NDAC74H0123456',
  },
];

const AUTOTRADER = [
  {
    // another duplicate of RAV4 – three sources will collapse to one card
    listingId: 'at-3001',
    title: '2022 Toyota RAV4 XLE Premium',
    year: 2022, make: 'Toyota', model: 'RAV4', trim: 'XLE Premium',
    price: 32200, mileage: 18420,
    bodyStyle: 'SUV', transmission: 'Automatic', fuelType: 'Gas', drivetrain: 'AWD',
    exteriorColor: 'Silver', interiorColor: 'Black',
    engine: '2.5L I4', mpgCity: 27, mpgHighway: 35,
    location: 'Austin, TX', dealerName: 'Lone Star Toyota', dealerPhone: '(512) 555-0142',
    description: 'Certified pre-owned RAV4 XLE Premium AWD – clean title, single owner.',
    imageUrl: IMG('rav4-1'), images: [IMG('rav4-1')],
    sourceUrl: 'https://www.autotrader.com/cars-for-sale/vehicledetails.xhtml?listingId=at-3001',
    sourceSite: 'AutoTrader',
    vin: 'JTMRWRFV2ND123456',
  },
  {
    listingId: 'at-3002',
    title: '2021 Chevrolet Silverado 1500 LT',
    year: 2021, make: 'Chevrolet', model: 'Silverado 1500', trim: 'LT',
    price: 38450, mileage: 33900,
    bodyStyle: 'Truck', transmission: 'Automatic', fuelType: 'Gas', drivetrain: '4WD',
    exteriorColor: 'Summit White', interiorColor: 'Jet Black',
    engine: '5.3L V8', mpgCity: 16, mpgHighway: 22,
    location: 'Dallas, TX', dealerName: 'Big D Chevrolet', dealerPhone: '(214) 555-0111',
    description: 'Silverado LT crew cab, Z71 off-road, trailering package.',
    imageUrl: IMG('silverado-2'), images: [IMG('silverado-2')],
    sourceUrl: 'https://www.autotrader.com/cars-for-sale/vehicledetails.xhtml?listingId=at-3002',
    sourceSite: 'AutoTrader',
    vin: '3GCUYDED7MG123456',
  },
  {
    listingId: 'at-3003',
    title: '2019 Volkswagen Golf GTI SE',
    year: 2019, make: 'Volkswagen', model: 'Golf GTI', trim: 'SE',
    price: 23990, mileage: 47200,
    bodyStyle: 'Hatchback', transmission: 'Manual', fuelType: 'Gas', drivetrain: 'FWD',
    exteriorColor: 'Pure White', interiorColor: 'Titan Black',
    engine: '2.0L Turbo I4', mpgCity: 24, mpgHighway: 32,
    location: 'Boston, MA', dealerName: 'Beacon Hill VW', dealerPhone: '(617) 555-0177',
    description: 'GTI SE 6-speed manual, sunroof, leather, performance pack.',
    imageUrl: IMG('gti-3'), images: [IMG('gti-3')],
    sourceUrl: 'https://www.autotrader.com/cars-for-sale/vehicledetails.xhtml?listingId=at-3003',
    sourceSite: 'AutoTrader',
    vin: '3VW547AU1KM123456',
  },
  {
    listingId: 'at-3004',
    title: '2023 Toyota Prius LE',
    year: 2023, make: 'Toyota', model: 'Prius', trim: 'LE',
    price: 28990, mileage: 7500,
    bodyStyle: 'Hatchback', transmission: 'CVT', fuelType: 'Hybrid', drivetrain: 'FWD',
    exteriorColor: 'Wind Chill Pearl', interiorColor: 'Black',
    engine: '2.0L Hybrid I4', mpgCity: 57, mpgHighway: 56,
    location: 'San Francisco, CA', dealerName: 'Golden Gate Toyota', dealerPhone: '(415) 555-0166',
    description: 'New-generation Prius LE, Toyota Safety Sense 3.0, Apple CarPlay.',
    imageUrl: IMG('prius-4'), images: [IMG('prius-4')],
    sourceUrl: 'https://www.autotrader.com/cars-for-sale/vehicledetails.xhtml?listingId=at-3004',
    sourceSite: 'AutoTrader',
    vin: 'JTDACAAU7P3123456',
  },
  {
    listingId: 'at-3005',
    title: '2020 Audi Q5 Premium Plus',
    year: 2020, make: 'Audi', model: 'Q5', trim: 'Premium Plus',
    price: 34990, mileage: 36100,
    bodyStyle: 'SUV', transmission: 'Automatic', fuelType: 'Gas', drivetrain: 'AWD',
    exteriorColor: 'Mythos Black', interiorColor: 'Atlas Beige',
    engine: '2.0L Turbo I4', mpgCity: 22, mpgHighway: 28,
    location: 'New York, NY', dealerName: 'Manhattan Audi', dealerPhone: '(212) 555-0144',
    description: 'Q5 Premium Plus, Bang & Olufsen audio, virtual cockpit, navigation.',
    imageUrl: IMG('q5-5'), images: [IMG('q5-5')],
    sourceUrl: 'https://www.autotrader.com/cars-for-sale/vehicledetails.xhtml?listingId=at-3005',
    sourceSite: 'AutoTrader',
    vin: 'WA1BNAFY8L2123456',
  },
];

export const fixtures = {
  'Cars.com': CARS_COM,
  'CarGurus': CARGURUS,
  'AutoTrader': AUTOTRADER,
};
